# Generated by Django 3.1.7 on 2021-03-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='geboorte_datum',
            new_name='birthday_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='naam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gebruiker',
            new_name='user',
        ),
    ]
